//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PSSEntities1 : DbContext
    {
        public PSSEntities1()
            : base("name=PSSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<ClientKind> ClientKind { get; set; }
        public virtual DbSet<Depot> Depot { get; set; }
        public virtual DbSet<Emp> Emp { get; set; }
        public virtual DbSet<InDepot> InDepot { get; set; }
        public virtual DbSet<InDepotDetail> InDepotDetail { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<OutDepot> OutDepot { get; set; }
        public virtual DbSet<OutDepotDetail> OutDepotDetail { get; set; }
        public virtual DbSet<Power> Power { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ProductKind> ProductKind { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Supplier> Supplier { get; set; }
        public virtual DbSet<SupplierKind> SupplierKind { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
        public virtual DbSet<TransferDetail> TransferDetail { get; set; }
        public virtual DbSet<v_Product> v_Product { get; set; }
    }
}
